name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: SOUMYA074
          outputs: dist/snake.svg
      - name: Upload snake animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg
